### PR TITLE
Fix immer version from showing up as critical during npm audit

### PR DESCRIPTION
**Pull request by thepoppingone**
Using https://www.npmjs.com/package/npm-force-resolutions to fix immerjs npm audit finding

### CODE REVIEW

**Comment by rikimaru0345** [comment]
@thepoppingone 

Thanks for the PR.

Can you please revert package lock completely?
I'll update package lock myself when I have some time to test the PR. 

Otherwise seems fine 👍

**Comment by thepoppingone** [comment]
The package lock is now reverted completely. Thanks for reviewing!

**Comment by thepoppingone** [comment]
Another note though:

When running this locally at the current stage there will be no issues, however, when building the image using Docker at 
https://github.com/cloudhut/kowl/blob/master/Dockerfile#L28

`npm install` will fail due to the stage `preinstall` is not allowed. The current workaround I found is to include the flag  `--unsafe-perm` to `npm install`. 

If you need me to include this in the PR, do let me know, this is dependent on the container used. I am using `node:17-alpine3.14`

**Comment by thepoppingone** [comment]
bump!

**Comment by rikimaru0345** [comment]
Sorry for the delay!
I will take care of it in a few hours.

**Comment by rikimaru0345** [comment]
Ok, I checked it, seems good!

**Pull request merged**
