### PR TITLE
Add OPT-NC at companies using Kowl

### PR DESCRIPTION
**Pull request by adriens**
Hi, we are currently using Kowl on the following environments at [opt-nc](https://github.com/opt-nc) : 

- Developer workstation
- Integration
- Testing
- Production

Thanks for delivering this product as an open source software.

### CODE REVIEW

**Comment by adriens** [comment]
cf #331

**Comment by weeco** [comment]
Thanks for adding this @adriens 🔥

**Comment by adriens** [comment]
@weeco : thanks for the great product... and for sharing your public product roadmap :1st_place_medal:

**Comment by adriens** [comment]
[tweet](https://twitter.com/rastadidi/status/1509637395909525532)
[linkedIn post](https://www.linkedin.com/posts/adrien-sales_stack-pullrequest-devops-activity-6915403021669580800-IisF?utm_source=linkedin_share&utm_medium=member_desktop_web)

**Pull request merged**
